DEBUG 2025-01-23 16:35:33.598 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-23 16:35:33.599 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-23 16:35:33.599 UTC: 	 Not using Singularity
DEBUG 2025-01-23 16:35:33.599 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-23 16:35:33.599 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-23 16:35:33.599 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-23 16:35:33.600 UTC: 	 Will use CRAB configuration file crab_TenMuE_0_200_Phase2.py
DEBUG 2025-01-23 16:35:33.600 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-23 16:35:33.604 UTC: 	 Will use CRAB plugin PRIVATEMC (i.e. will run an a MC generation job type).
ERROR 2025-01-23 16:35:33.604 UTC: 	 Task requests 8000 MB of memory, above the allowed maximum of 5000 for a 1 core(s) job.

The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-01-23 16:35:33.604 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Task requests 8000 MB of memory, above the allowed maximum of 5000 for a 1 core(s) job.

The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-01-23 16:35:33.608 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab.log
DEBUG 2025-01-24 08:19:17.274 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-24 08:19:17.275 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-24 08:19:17.275 UTC: 	 Not using Singularity
DEBUG 2025-01-24 08:19:17.275 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-24 08:19:17.275 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-24 08:19:17.276 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-24 08:19:17.278 UTC: 	 Will use CRAB configuration file crab_TenMuE_0_200_Phase2_step1_cfg.py
DEBUG 2025-01-24 08:19:17.278 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-24 08:19:17.285 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-24 08:19:17.286 UTC: 	 Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-01-24 08:19:17.286 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-01-24 08:19:17.294 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab.log
DEBUG 2025-01-24 08:20:53.374 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-24 08:20:53.374 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-24 08:20:53.374 UTC: 	 Not using Singularity
DEBUG 2025-01-24 08:20:53.374 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-24 08:20:53.374 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-24 08:20:53.375 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-24 08:20:53.377 UTC: 	 Will use CRAB configuration file crab_TenMuE_0_200_Phase2_step1_cfg.py
DEBUG 2025-01-24 08:20:53.377 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-24 08:20:53.383 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-24 08:20:53.386 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_projects/crab_140X_mcRun4_TenMuE_0_200_GEN-SIM-DIGI-RAW' already exists 
Please change the requestName in the config file
ERROR 2025-01-24 08:20:53.387 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_projects/crab_140X_mcRun4_TenMuE_0_200_GEN-SIM-DIGI-RAW' already exists 
Please change the requestName in the config file
INFO 2025-01-24 08:20:53.411 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab.log
DEBUG 2025-01-24 08:45:25.379 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-24 08:45:25.379 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-24 08:45:25.379 UTC: 	 Not using Singularity
DEBUG 2025-01-24 08:45:25.379 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-24 08:45:25.380 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-24 08:45:25.380 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-24 08:45:25.381 UTC: 	 Will use CRAB configuration file crab_TenMuE_0_200_Phase2_step1_cfg.py
DEBUG 2025-01-24 08:45:25.382 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-24 08:45:25.391 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-24 08:45:25.393 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_projects/crab_140X_mcRun4_TenMuE_0_200_GEN-SIM-DIGI-RAW' already exists 
Please change the requestName in the config file
ERROR 2025-01-24 08:45:25.393 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_projects/crab_140X_mcRun4_TenMuE_0_200_GEN-SIM-DIGI-RAW' already exists 
Please change the requestName in the config file
INFO 2025-01-24 08:45:25.419 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab.log
DEBUG 2025-01-24 09:05:22.331 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-24 09:05:22.331 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-24 09:05:22.331 UTC: 	 Not using Singularity
DEBUG 2025-01-24 09:05:22.331 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-24 09:05:22.331 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-24 09:05:22.333 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-24 09:05:22.334 UTC: 	 Will use CRAB configuration file crab_TenMuE_0_200_Phase2_step1_cfg.py
DEBUG 2025-01-24 09:05:22.334 UTC: 	 Loading CRAB configuration file.
ERROR 2025-01-24 09:05:22.342 UTC: 	 Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-01-24 09:05:22.342 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_TenMuE_0_200_Phase2_step1_cfg.py", line 12, in <module>
    config.allowNonValidInputDataset = True
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 263, in __setattr__
    raise RuntimeError(msg)
RuntimeError: Can only add objects of type ConfigSection to Configuration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_TenMuE_0_200_Phase2_step1_cfg.py
Due to error:
Can only add objects of type ConfigSection to ConfigurationTraceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_TenMuE_0_200_Phase2_step1_cfg.py", line 12, in <module>
    config.allowNonValidInputDataset = True
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 263, in __setattr__
    raise RuntimeError(msg)
RuntimeError: Can only add objects of type ConfigSection to Configuration


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
Can only add objects of type ConfigSection to Configuration
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-01-24 09:05:22.364 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab.log
DEBUG 2025-01-24 18:38:11.032 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-24 18:38:11.032 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-24 18:38:11.032 UTC: 	 Not using Singularity
DEBUG 2025-01-24 18:38:11.032 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-24 18:38:11.032 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-24 18:38:11.032 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
ERROR 2025-01-24 18:38:11.034 UTC: 	 CRAB configuration file crabConfig.py not found.
ERROR 2025-01-24 18:38:11.034 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
CRABClient.ClientExceptions.ConfigurationException: CRAB configuration file crabConfig.py not found.
INFO 2025-01-24 18:38:11.049 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab.log
DEBUG 2025-01-25 13:02:21.094 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-25 13:02:21.094 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-25 13:02:21.094 UTC: 	 Not using Singularity
DEBUG 2025-01-25 13:02:21.094 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-25 13:02:21.094 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-25 13:02:21.094 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-25 13:02:21.096 UTC: 	 Will use CRAB configuration file crab_TenMuE_0_200_Phase2_step2_cfg.py
DEBUG 2025-01-25 13:02:21.096 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-25 13:02:21.102 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-25 13:02:21.102 UTC: 	 Task requests 6000 MB of memory, above the allowed maximum of 5000 for a 1 core(s) job.

The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-01-25 13:02:21.102 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Task requests 6000 MB of memory, above the allowed maximum of 5000 for a 1 core(s) job.

The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-01-25 13:02:21.191 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab.log
DEBUG 2025-01-25 13:25:04.274 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-25 13:25:04.274 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-25 13:25:04.274 UTC: 	 Not using Singularity
DEBUG 2025-01-25 13:25:04.274 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-25 13:25:04.274 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-25 13:25:04.274 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-25 13:25:04.275 UTC: 	 Will use CRAB configuration file crab_TenMuE_0_200_Phase2_step2_cfg.py
DEBUG 2025-01-25 13:25:04.275 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-25 13:25:04.279 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-25 13:25:04.279 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_projects/crab_140X_mcRun4_TenMuE_0_200_GEN-SIM-DIGI-RAW' already exists 
Please change the requestName in the config file
ERROR 2025-01-25 13:25:04.279 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_projects/crab_140X_mcRun4_TenMuE_0_200_GEN-SIM-DIGI-RAW' already exists 
Please change the requestName in the config file
INFO 2025-01-25 13:25:04.282 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab.log
DEBUG 2025-01-25 13:29:48.954 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-25 13:29:48.955 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-25 13:29:48.955 UTC: 	 Not using Singularity
DEBUG 2025-01-25 13:29:48.955 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-25 13:29:48.955 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-25 13:29:48.955 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-25 13:29:48.956 UTC: 	 Will use CRAB configuration file crab_TenMuE_0_200_Phase2_step2_cfg.py
DEBUG 2025-01-25 13:29:48.956 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-25 13:29:48.957 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-25 13:29:48.957 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_projects/crab_140X_mcRun4_TenMuE_0_200_GEN-SIM-DIGI-RAW' already exists 
Please change the requestName in the config file
ERROR 2025-01-25 13:29:48.957 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_projects/crab_140X_mcRun4_TenMuE_0_200_GEN-SIM-DIGI-RAW' already exists 
Please change the requestName in the config file
INFO 2025-01-25 13:29:49.007 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab.log
DEBUG 2025-01-25 17:12:42.067 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-25 17:12:42.068 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-25 17:12:42.068 UTC: 	 Not using Singularity
DEBUG 2025-01-25 17:12:42.068 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-25 17:12:42.068 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-25 17:12:42.068 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-25 17:12:42.069 UTC: 	 Will use CRAB configuration file crab_TenMuE_0_200_Phase2_step2_cfg.py
DEBUG 2025-01-25 17:12:42.069 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-25 17:12:42.071 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-25 17:12:42.071 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_projects/crab_140X_mcRun4_TenMuE_0_200_RECO_RECOSIM_PAT_VALIDATION_DQM' already exists 
Please change the requestName in the config file
ERROR 2025-01-25 17:12:42.071 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab_projects/crab_140X_mcRun4_TenMuE_0_200_RECO_RECOSIM_PAT_VALIDATION_DQM' already exists 
Please change the requestName in the config file
INFO 2025-01-25 17:12:42.096 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/Utilities/run_the_matrix/29621.0_TenMuE_0_200+2026D110/crab.log
