DEBUG 2024-12-11 10:35:41.220 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:35:41.220 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:35:41.220 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:35:41.220 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:35:41.220 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:35:41.220 UTC: 	 Could not find CRAB cache file /lustrehome/felicenenna/.crab3; creating a new one.
ERROR 2024-12-11 10:35:41.226 UTC: 	 CRAB configuration file crab_MCRun4_BdTau3mu_cfg.py not found.
ERROR 2024-12-11 10:35:41.226 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
CRABClient.ClientExceptions.ConfigurationException: CRAB configuration file crab_MCRun4_BdTau3mu_cfg.py not found.
INFO 2024-12-11 10:35:41.230 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:35:49.657 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:35:49.657 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:35:49.657 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:35:49.657 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:35:49.657 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:35:49.657 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
ERROR 2024-12-11 10:35:49.659 UTC: 	 CRAB configuration file crab_MCRun4_BuTau3mu_cfg.py not found.
ERROR 2024-12-11 10:35:49.659 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
CRABClient.ClientExceptions.ConfigurationException: CRAB configuration file crab_MCRun4_BuTau3mu_cfg.py not found.
INFO 2024-12-11 10:35:49.664 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:35:58.203 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:35:58.203 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:35:58.203 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:35:58.203 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:35:58.203 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:35:58.203 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
ERROR 2024-12-11 10:35:58.204 UTC: 	 CRAB configuration file crab_MCRun4_DsTau3mu_cfg.py not found.
ERROR 2024-12-11 10:35:58.205 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
CRABClient.ClientExceptions.ConfigurationException: CRAB configuration file crab_MCRun4_DsTau3mu_cfg.py not found.
INFO 2024-12-11 10:35:58.208 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:36:32.428 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:36:32.429 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:36:32.429 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:36:32.429 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:36:32.429 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:36:32.430 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:36:32.433 UTC: 	 Will use CRAB configuration file crab_MCRun4_BdTau3Mu_cfg.py
DEBUG 2024-12-11 10:36:32.433 UTC: 	 Loading CRAB configuration file.
ERROR 2024-12-11 10:36:32.440 UTC: 	 Error while loading CRAB configuration:
EOL while scanning string literal (crab_MCRun4_BdTau3Mu_cfg.py, line 23)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-12-11 10:36:32.440 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BdTau3Mu_cfg.py", line 23
    config.Data.outputDatasetTag = "BdTau3mu_MCRun4'
                                                    ^
SyntaxError: EOL while scanning string literal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BdTau3Mu_cfg.py
Due to error:
EOL while scanning string literal (crab_MCRun4_BdTau3Mu_cfg.py, line 23)Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BdTau3Mu_cfg.py", line 23
    config.Data.outputDatasetTag = "BdTau3mu_MCRun4'
                                                    ^
SyntaxError: EOL while scanning string literal


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
EOL while scanning string literal (crab_MCRun4_BdTau3Mu_cfg.py, line 23)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-12-11 10:36:32.451 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:36:41.068 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:36:41.068 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:36:41.068 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:36:41.068 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:36:41.068 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:36:41.069 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:36:41.070 UTC: 	 Will use CRAB configuration file crab_MCRun4_BuTau3Mu_cfg.py
DEBUG 2024-12-11 10:36:41.070 UTC: 	 Loading CRAB configuration file.
ERROR 2024-12-11 10:36:41.075 UTC: 	 Error while loading CRAB configuration:
EOL while scanning string literal (crab_MCRun4_BuTau3Mu_cfg.py, line 23)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-12-11 10:36:41.075 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BuTau3Mu_cfg.py", line 23
    config.Data.outputDatasetTag = "BuTau3mu_MCRun4'
                                                    ^
SyntaxError: EOL while scanning string literal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BuTau3Mu_cfg.py
Due to error:
EOL while scanning string literal (crab_MCRun4_BuTau3Mu_cfg.py, line 23)Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BuTau3Mu_cfg.py", line 23
    config.Data.outputDatasetTag = "BuTau3mu_MCRun4'
                                                    ^
SyntaxError: EOL while scanning string literal


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
EOL while scanning string literal (crab_MCRun4_BuTau3Mu_cfg.py, line 23)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-12-11 10:36:41.079 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:36:49.589 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:36:49.590 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:36:49.590 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:36:49.590 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:36:49.590 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:36:49.591 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:36:49.595 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_cfg.py
DEBUG 2024-12-11 10:36:49.596 UTC: 	 Loading CRAB configuration file.
ERROR 2024-12-11 10:36:49.602 UTC: 	 Error while loading CRAB configuration:
EOL while scanning string literal (crab_MCRun4_DsTau3Mu_cfg.py, line 23)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-12-11 10:36:49.602 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_DsTau3Mu_cfg.py", line 23
    config.Data.outputDatasetTag = "DsTau3mu_MCRun4'
                                                    ^
SyntaxError: EOL while scanning string literal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_DsTau3Mu_cfg.py
Due to error:
EOL while scanning string literal (crab_MCRun4_DsTau3Mu_cfg.py, line 23)Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_DsTau3Mu_cfg.py", line 23
    config.Data.outputDatasetTag = "DsTau3mu_MCRun4'
                                                    ^
SyntaxError: EOL while scanning string literal


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
EOL while scanning string literal (crab_MCRun4_DsTau3Mu_cfg.py, line 23)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-12-11 10:36:49.606 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:38:32.166 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:38:32.166 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:38:32.166 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:38:32.166 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:38:32.167 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:38:32.168 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:38:32.169 UTC: 	 Will use CRAB configuration file crab_MCRun4_BdTau3Mu_cfg.py
DEBUG 2024-12-11 10:38:32.169 UTC: 	 Loading CRAB configuration file.
ERROR 2024-12-11 10:38:32.255 UTC: 	 Error while loading CRAB configuration:
No module named 'config_info'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-12-11 10:38:32.255 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BdTau3Mu_cfg.py", line 3, in <module>
    import config_info
ModuleNotFoundError: No module named 'config_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BdTau3Mu_cfg.py
Due to error:
No module named 'config_info'Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BdTau3Mu_cfg.py", line 3, in <module>
    import config_info
ModuleNotFoundError: No module named 'config_info'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
No module named 'config_info'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-12-11 10:38:32.269 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:38:41.293 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:38:41.294 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:38:41.294 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:38:41.294 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:38:41.294 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:38:41.295 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:38:41.297 UTC: 	 Will use CRAB configuration file crab_MCRun4_BuTau3Mu_cfg.py
DEBUG 2024-12-11 10:38:41.297 UTC: 	 Loading CRAB configuration file.
ERROR 2024-12-11 10:38:41.418 UTC: 	 Error while loading CRAB configuration:
No module named 'config_info'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-12-11 10:38:41.419 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BuTau3Mu_cfg.py", line 3, in <module>
    import config_info
ModuleNotFoundError: No module named 'config_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BuTau3Mu_cfg.py
Due to error:
No module named 'config_info'Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BuTau3Mu_cfg.py", line 3, in <module>
    import config_info
ModuleNotFoundError: No module named 'config_info'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
No module named 'config_info'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-12-11 10:38:41.440 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:38:50.270 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:38:50.270 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:38:50.270 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:38:50.270 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:38:50.270 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:38:50.270 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:38:50.272 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_cfg.py
DEBUG 2024-12-11 10:38:50.272 UTC: 	 Loading CRAB configuration file.
ERROR 2024-12-11 10:38:50.363 UTC: 	 Error while loading CRAB configuration:
No module named 'config_info'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-12-11 10:38:50.363 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_DsTau3Mu_cfg.py", line 3, in <module>
    import config_info
ModuleNotFoundError: No module named 'config_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_DsTau3Mu_cfg.py
Due to error:
No module named 'config_info'Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_DsTau3Mu_cfg.py", line 3, in <module>
    import config_info
ModuleNotFoundError: No module named 'config_info'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
No module named 'config_info'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-12-11 10:38:50.367 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:42:20.935 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:42:20.936 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:42:20.936 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:42:20.936 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:42:20.936 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:42:20.936 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:42:20.937 UTC: 	 Will use CRAB configuration file crab_MCRun4_BdTau3Mu_cfg.py
DEBUG 2024-12-11 10:42:20.937 UTC: 	 Loading CRAB configuration file.
ERROR 2024-12-11 10:42:21.009 UTC: 	 Error while loading CRAB configuration:
No module named 'config_info'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-12-11 10:42:21.009 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BdTau3Mu_cfg.py", line 3, in <module>
    import config_info
ModuleNotFoundError: No module named 'config_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BdTau3Mu_cfg.py
Due to error:
No module named 'config_info'Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BdTau3Mu_cfg.py", line 3, in <module>
    import config_info
ModuleNotFoundError: No module named 'config_info'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
No module named 'config_info'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-12-11 10:42:21.014 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:42:29.316 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:42:29.316 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:42:29.316 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:42:29.316 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:42:29.316 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:42:29.317 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:42:29.317 UTC: 	 Will use CRAB configuration file crab_MCRun4_BuTau3Mu_cfg.py
DEBUG 2024-12-11 10:42:29.317 UTC: 	 Loading CRAB configuration file.
ERROR 2024-12-11 10:42:29.390 UTC: 	 Error while loading CRAB configuration:
No module named 'config_info'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-12-11 10:42:29.390 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BuTau3Mu_cfg.py", line 3, in <module>
    import config_info
ModuleNotFoundError: No module named 'config_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BuTau3Mu_cfg.py
Due to error:
No module named 'config_info'Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_BuTau3Mu_cfg.py", line 3, in <module>
    import config_info
ModuleNotFoundError: No module named 'config_info'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
No module named 'config_info'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-12-11 10:42:29.394 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:42:37.678 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:42:37.678 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:42:37.678 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:42:37.678 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:42:37.679 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:42:37.679 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:42:37.679 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_cfg.py
DEBUG 2024-12-11 10:42:37.680 UTC: 	 Loading CRAB configuration file.
ERROR 2024-12-11 10:42:37.736 UTC: 	 Error while loading CRAB configuration:
No module named 'config_info'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-12-11 10:42:37.736 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_DsTau3Mu_cfg.py", line 3, in <module>
    import config_info
ModuleNotFoundError: No module named 'config_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_DsTau3Mu_cfg.py
Due to error:
No module named 'config_info'Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_DsTau3Mu_cfg.py", line 3, in <module>
    import config_info
ModuleNotFoundError: No module named 'config_info'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
No module named 'config_info'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-12-11 10:42:37.739 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:46:41.743 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:46:41.744 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:46:41.744 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:46:41.744 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:46:41.744 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:46:41.744 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:46:41.745 UTC: 	 Will use CRAB configuration file crab_MCRun4_BdTau3Mu_cfg.py
DEBUG 2024-12-11 10:46:41.745 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 10:46:41.783 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 10:46:41.783 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_SkimTau3mu_MCRun4_BdTau3Mu' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 10:46:41.783 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_SkimTau3mu_MCRun4_BdTau3Mu' already exists 
Please change the requestName in the config file
INFO 2024-12-11 10:46:41.786 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:46:49.705 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:46:49.705 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:46:49.705 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:46:49.705 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:46:49.705 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:46:49.705 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:46:49.706 UTC: 	 Will use CRAB configuration file crab_MCRun4_BuTau3Mu_cfg.py
DEBUG 2024-12-11 10:46:49.706 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 10:46:49.743 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 10:46:49.744 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_SkimTau3mu_MCRun4_BuTau3Mu' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 10:46:49.744 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_SkimTau3mu_MCRun4_BuTau3Mu' already exists 
Please change the requestName in the config file
INFO 2024-12-11 10:46:49.747 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:46:57.955 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:46:57.956 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:46:57.956 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:46:57.956 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:46:57.956 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:46:57.956 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:46:57.957 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_cfg.py
DEBUG 2024-12-11 10:46:57.957 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 10:46:57.989 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 10:46:57.989 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_SkimTau3mu_MCRun4_DsTau3Mu' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 10:46:57.989 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_SkimTau3mu_MCRun4_DsTau3Mu' already exists 
Please change the requestName in the config file
INFO 2024-12-11 10:46:57.992 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:54:43.831 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:54:43.831 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:54:43.831 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:54:43.831 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:54:43.831 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:54:43.832 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:54:43.832 UTC: 	 Will use CRAB configuration file crab_MCRun4_BdTau3Mu_cfg.py
DEBUG 2024-12-11 10:54:43.833 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 10:54:43.866 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 10:54:43.867 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_SkimTau3mu_MCRun4_BdTau3Mu' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 10:54:43.867 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_SkimTau3mu_MCRun4_BdTau3Mu' already exists 
Please change the requestName in the config file
INFO 2024-12-11 10:54:43.870 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:54:51.607 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:54:51.608 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:54:51.608 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:54:51.608 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:54:51.608 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:54:51.608 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:54:51.609 UTC: 	 Will use CRAB configuration file crab_MCRun4_BuTau3Mu_cfg.py
DEBUG 2024-12-11 10:54:51.609 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 10:54:51.637 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 10:54:51.638 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_SkimTau3mu_MCRun4_BuTau3Mu' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 10:54:51.639 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_SkimTau3mu_MCRun4_BuTau3Mu' already exists 
Please change the requestName in the config file
INFO 2024-12-11 10:54:51.642 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 10:54:59.456 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 10:54:59.457 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 10:54:59.457 UTC: 	 Not using Singularity
DEBUG 2024-12-11 10:54:59.457 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 10:54:59.457 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 10:54:59.457 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 10:54:59.458 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_cfg.py
DEBUG 2024-12-11 10:54:59.458 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 10:54:59.489 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 10:54:59.490 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_SkimTau3mu_MCRun4_DsTau3Mu' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 10:54:59.491 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_SkimTau3mu_MCRun4_DsTau3Mu' already exists 
Please change the requestName in the config file
INFO 2024-12-11 10:54:59.494 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 11:07:44.437 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 11:07:44.437 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 11:07:44.437 UTC: 	 Not using Singularity
DEBUG 2024-12-11 11:07:44.438 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 11:07:44.438 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 11:07:44.438 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 11:07:44.441 UTC: 	 Will use CRAB configuration file crab_MCRun4_BdTau3Mu_cfg.py
DEBUG 2024-12-11 11:07:44.441 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 11:07:44.516 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 11:07:44.516 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_Tau3mu_MCRun4_BdTau3Mu_private' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 11:07:44.516 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_Tau3mu_MCRun4_BdTau3Mu_private' already exists 
Please change the requestName in the config file
INFO 2024-12-11 11:07:44.556 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 11:07:53.449 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 11:07:53.450 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 11:07:53.450 UTC: 	 Not using Singularity
DEBUG 2024-12-11 11:07:53.450 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 11:07:53.450 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 11:07:53.450 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 11:07:53.451 UTC: 	 Will use CRAB configuration file crab_MCRun4_BuTau3Mu_cfg.py
DEBUG 2024-12-11 11:07:53.451 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 11:07:53.508 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 11:07:53.508 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_BuTau3Mu_private' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 11:07:53.508 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_BuTau3Mu_private' already exists 
Please change the requestName in the config file
INFO 2024-12-11 11:07:53.546 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 11:08:02.124 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 11:08:02.124 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 11:08:02.124 UTC: 	 Not using Singularity
DEBUG 2024-12-11 11:08:02.125 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 11:08:02.125 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 11:08:02.125 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 11:08:02.126 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_cfg.py
DEBUG 2024-12-11 11:08:02.127 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 11:08:02.179 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 11:08:02.180 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_DsTau3Mu_private' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 11:08:02.180 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_DsTau3Mu_private' already exists 
Please change the requestName in the config file
INFO 2024-12-11 11:08:02.184 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 11:23:03.208 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 11:23:03.208 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 11:23:03.208 UTC: 	 Not using Singularity
DEBUG 2024-12-11 11:23:03.208 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 11:23:03.208 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 11:23:03.211 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 11:23:03.217 UTC: 	 Will use CRAB configuration file crab_MCRun4_BdTau3Mu_cfg.py
DEBUG 2024-12-11 11:23:03.218 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 11:23:03.288 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 11:23:03.288 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_Tau3mu_MCRun4_BdTau3Mu_private' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 11:23:03.288 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_Tau3mu_MCRun4_BdTau3Mu_private' already exists 
Please change the requestName in the config file
INFO 2024-12-11 11:23:03.322 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 11:23:12.731 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 11:23:12.731 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 11:23:12.731 UTC: 	 Not using Singularity
DEBUG 2024-12-11 11:23:12.731 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 11:23:12.731 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 11:23:12.732 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 11:23:12.735 UTC: 	 Will use CRAB configuration file crab_MCRun4_BuTau3Mu_cfg.py
DEBUG 2024-12-11 11:23:12.736 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 11:23:12.822 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 11:23:12.822 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_BuTau3Mu_private' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 11:23:12.822 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_BuTau3Mu_private' already exists 
Please change the requestName in the config file
INFO 2024-12-11 11:23:12.826 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 11:23:22.524 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 11:23:22.524 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 11:23:22.524 UTC: 	 Not using Singularity
DEBUG 2024-12-11 11:23:22.524 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 11:23:22.524 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 11:23:22.525 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 11:23:22.540 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_cfg.py
DEBUG 2024-12-11 11:23:22.540 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 11:23:22.622 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 11:23:22.622 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_DsTau3Mu_private' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 11:23:22.623 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_DsTau3Mu_private' already exists 
Please change the requestName in the config file
INFO 2024-12-11 11:23:22.629 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 15:50:30.470 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 15:50:30.471 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 15:50:30.471 UTC: 	 Not using Singularity
DEBUG 2024-12-11 15:50:30.471 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 15:50:30.471 UTC: 	 Executing command: 'kill'
DEBUG 2024-12-11 15:50:30.471 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
DEBUG 2024-12-11 15:51:03.080 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 15:51:03.080 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 15:51:03.080 UTC: 	 Not using Singularity
DEBUG 2024-12-11 15:51:03.080 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 15:51:03.080 UTC: 	 Executing command: 'kill'
DEBUG 2024-12-11 15:51:03.081 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
ERROR 2024-12-11 15:51:03.082 UTC: 	 Cannot find .requestcache file in CRAB project directory /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects
ERROR 2024-12-11 15:51:03.082 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 695, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 537, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects
INFO 2024-12-11 15:51:03.097 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 18:49:46.964 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 18:49:46.964 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 18:49:46.964 UTC: 	 Not using Singularity
DEBUG 2024-12-11 18:49:46.964 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 18:49:46.964 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 18:49:46.964 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 18:49:46.967 UTC: 	 Will use CRAB configuration file crab_MCRun4_BdTau3Mu_cfg.py
DEBUG 2024-12-11 18:49:46.967 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 18:49:47.016 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 18:49:47.019 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_BdTau3Mu_private' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 18:49:47.019 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_BdTau3Mu_private' already exists 
Please change the requestName in the config file
INFO 2024-12-11 18:49:47.023 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 18:49:55.299 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 18:49:55.299 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 18:49:55.299 UTC: 	 Not using Singularity
DEBUG 2024-12-11 18:49:55.299 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 18:49:55.299 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 18:49:55.299 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 18:49:55.300 UTC: 	 Will use CRAB configuration file crab_MCRun4_BuTau3Mu_cfg.py
DEBUG 2024-12-11 18:49:55.300 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 18:49:55.353 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 18:49:55.355 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_BuTau3Mu_private' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 18:49:55.356 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_BuTau3Mu_private' already exists 
Please change the requestName in the config file
INFO 2024-12-11 18:49:55.361 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 18:50:03.861 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 18:50:03.861 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 18:50:03.861 UTC: 	 Not using Singularity
DEBUG 2024-12-11 18:50:03.861 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 18:50:03.861 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-11 18:50:03.861 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-11 18:50:03.862 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_cfg.py
DEBUG 2024-12-11 18:50:03.862 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-11 18:50:03.900 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-11 18:50:03.902 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_DsTau3Mu_private' already exists 
Please change the requestName in the config file
ERROR 2024-12-11 18:50:03.902 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_DsTau3Mu_private' already exists 
Please change the requestName in the config file
INFO 2024-12-11 18:50:03.907 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-11 18:51:48.633 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-11 18:51:48.634 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-11 18:51:48.634 UTC: 	 Not using Singularity
DEBUG 2024-12-11 18:51:48.634 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-11 18:51:48.634 UTC: 	 Executing command: 'kill'
DEBUG 2024-12-11 18:51:48.634 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
ERROR 2024-12-11 18:51:48.635 UTC: 	 Cannot find .requestcache file in CRAB project directory /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_BuTau3Mu_private
ERROR 2024-12-11 18:51:48.635 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 695, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 537, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_BuTau3Mu_private
INFO 2024-12-11 18:51:48.639 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2024-12-17 21:13:11.643 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-17 21:13:11.643 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-17 21:13:11.643 UTC: 	 Not using Singularity
DEBUG 2024-12-17 21:13:11.643 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-17 21:13:11.643 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-17 21:13:11.643 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2024-12-17 21:13:11.645 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_cfg.py
DEBUG 2024-12-17 21:13:11.645 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-17 21:13:11.682 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-17 21:13:11.684 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_DsTau3Mu_private' already exists 
Please change the requestName in the config file
ERROR 2024-12-17 21:13:11.684 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_MCRun4_DsTau3Mu_private' already exists 
Please change the requestName in the config file
INFO 2024-12-17 21:13:11.716 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-01-26 10:39:59.428 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-26 10:39:59.428 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-26 10:39:59.428 UTC: 	 Not using Singularity
DEBUG 2025-01-26 10:39:59.428 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-26 10:39:59.428 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-26 10:39:59.428 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-26 10:39:59.429 UTC: 	 Will use CRAB configuration file crab_Ana_TenMuE_0_200_RECO_Phase2_cfg.py
DEBUG 2025-01-26 10:39:59.430 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-26 10:39:59.463 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-26 10:39:59.463 UTC: 	 Invalid CRAB configuration: Parameter Site.storageSite is missing.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-01-26 10:39:59.463 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: Parameter Site.storageSite is missing.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-01-26 10:39:59.484 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-01-26 10:43:21.489 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-26 10:43:21.490 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-26 10:43:21.490 UTC: 	 Not using Singularity
DEBUG 2025-01-26 10:43:21.490 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-26 10:43:21.490 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-26 10:43:21.490 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-26 10:43:21.491 UTC: 	 Will use CRAB configuration file crab_Ana_TenMuE_0_200_RECO_Phase2_cfg.py
DEBUG 2025-01-26 10:43:21.491 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-26 10:43:21.521 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-26 10:43:21.522 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcRun4_TenMuE_0_200_RECO_ANA' already exists 
Please change the requestName in the config file
ERROR 2025-01-26 10:43:21.522 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcRun4_TenMuE_0_200_RECO_ANA' already exists 
Please change the requestName in the config file
INFO 2025-01-26 10:43:21.545 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-01-26 10:53:52.394 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-26 10:53:52.394 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-26 10:53:52.394 UTC: 	 Not using Singularity
DEBUG 2025-01-26 10:53:52.394 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-26 10:53:52.394 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-26 10:53:52.395 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-26 10:53:52.395 UTC: 	 Will use CRAB configuration file crab_Ana_TenMuE_0_200_RECO_Phase2_cfg.py
DEBUG 2025-01-26 10:53:52.395 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-26 10:53:52.439 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-26 10:53:52.439 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcRun4_TenMuE_0_200_RECO_ANA' already exists 
Please change the requestName in the config file
ERROR 2025-01-26 10:53:52.439 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcRun4_TenMuE_0_200_RECO_ANA' already exists 
Please change the requestName in the config file
INFO 2025-01-26 10:53:52.462 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-01-26 10:59:46.440 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-26 10:59:46.440 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-26 10:59:46.440 UTC: 	 Not using Singularity
DEBUG 2025-01-26 10:59:46.440 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-26 10:59:46.440 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-26 10:59:46.441 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-26 10:59:46.442 UTC: 	 Will use CRAB configuration file crab_Ana_TenMuE_0_200_RECO_Phase2_cfg.py
DEBUG 2025-01-26 10:59:46.442 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-26 10:59:46.473 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-26 10:59:46.474 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcRun4_TenMuE_0_200_RECO_ANA' already exists 
Please change the requestName in the config file
ERROR 2025-01-26 10:59:46.474 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcRun4_TenMuE_0_200_RECO_ANA' already exists 
Please change the requestName in the config file
INFO 2025-01-26 10:59:46.477 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-01-26 12:49:28.769 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-26 12:49:28.769 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-26 12:49:28.769 UTC: 	 Not using Singularity
DEBUG 2025-01-26 12:49:28.769 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-26 12:49:28.769 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-26 12:49:28.769 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-26 12:49:28.770 UTC: 	 Will use CRAB configuration file crab_Ana_TenMuE_0_200_RECO_Phase2_cfg.py
DEBUG 2025-01-26 12:49:28.770 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-26 12:49:28.775 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-26 12:49:28.775 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcRun4_TenMuE_0_200_RECO_ANA' already exists 
Please change the requestName in the config file
ERROR 2025-01-26 12:49:28.775 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcRun4_TenMuE_0_200_RECO_ANA' already exists 
Please change the requestName in the config file
INFO 2025-01-26 12:49:28.794 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-01-27 21:00:44.310 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-27 21:00:44.310 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-27 21:00:44.310 UTC: 	 Not using Singularity
DEBUG 2025-01-27 21:00:44.310 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-27 21:00:44.310 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-27 21:00:44.310 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-27 21:00:44.311 UTC: 	 Will use CRAB configuration file crab_Ana_TenMuE_0_20_newMINIAOD_Phase2_cfg.py
DEBUG 2025-01-27 21:00:44.311 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-27 21:00:44.315 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-27 21:00:44.316 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcRun4_TenMuE_0_20_MINIAOD_ANA' already exists 
Please change the requestName in the config file
ERROR 2025-01-27 21:00:44.316 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcRun4_TenMuE_0_20_MINIAOD_ANA' already exists 
Please change the requestName in the config file
INFO 2025-01-27 21:00:44.332 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-01-30 13:44:51.649 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-30 13:44:51.650 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-30 13:44:51.650 UTC: 	 Not using Singularity
DEBUG 2025-01-30 13:44:51.650 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-30 13:44:51.650 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-30 13:44:51.652 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-30 13:44:51.654 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_RECO_cfg.py
DEBUG 2025-01-30 13:44:51.654 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-30 13:44:51.660 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-30 13:44:51.663 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_MCRun4_DsTau3Mu_private_newMINIAOD' already exists 
Please change the requestName in the config file
ERROR 2025-01-30 13:44:51.663 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_MCRun4_DsTau3Mu_private_newMINIAOD' already exists 
Please change the requestName in the config file
INFO 2025-01-30 13:44:51.697 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-01-30 13:54:48.191 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-30 13:54:48.191 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-30 13:54:48.192 UTC: 	 Not using Singularity
DEBUG 2025-01-30 13:54:48.192 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-30 13:54:48.192 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-30 13:54:48.192 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-30 13:54:48.193 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_RECO_cfg.py
DEBUG 2025-01-30 13:54:48.193 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-30 13:54:48.197 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-30 13:54:48.197 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_MCRun4_DsTau3Mu_private_newMINIAOD' already exists 
Please change the requestName in the config file
ERROR 2025-01-30 13:54:48.197 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_MCRun4_DsTau3Mu_private_newMINIAOD' already exists 
Please change the requestName in the config file
INFO 2025-01-30 13:54:48.222 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-01-30 14:44:23.543 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-01-30 14:44:23.543 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-01-30 14:44:23.543 UTC: 	 Not using Singularity
DEBUG 2025-01-30 14:44:23.543 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-01-30 14:44:23.543 UTC: 	 Executing command: 'submit'
DEBUG 2025-01-30 14:44:23.543 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-01-30 14:44:23.544 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_RECO_cfg.py
DEBUG 2025-01-30 14:44:23.544 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-01-30 14:44:23.552 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-01-30 14:44:23.552 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_MCRun4_DsTau3Mu_private_RECO' already exists 
Please change the requestName in the config file
ERROR 2025-01-30 14:44:23.552 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_MCRun4_DsTau3Mu_private_RECO' already exists 
Please change the requestName in the config file
INFO 2025-01-30 14:44:23.585 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-02-02 08:04:10.223 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-02-02 08:04:10.223 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-02-02 08:04:10.223 UTC: 	 Not using Singularity
DEBUG 2025-02-02 08:04:10.223 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-02-02 08:04:10.223 UTC: 	 Executing command: 'resubmit'
DEBUG 2025-02-02 08:04:10.223 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
DEBUG 2025-02-02 08:04:24.272 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-02-02 08:04:24.273 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-02-02 08:04:24.273 UTC: 	 Not using Singularity
DEBUG 2025-02-02 08:04:24.273 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-02-02 08:04:24.273 UTC: 	 Executing command: 'resubmit'
DEBUG 2025-02-02 08:04:24.273 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
ERROR 2025-02-02 08:04:24.275 UTC: 	 Error: crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py is not a valid CRAB project directory.
ERROR 2025-02-02 08:04:24.275 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/resubmit.py", line 30, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py is not a valid CRAB project directory.
INFO 2025-02-02 08:04:24.293 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-03-05 16:54:34.314 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-03-05 16:54:34.315 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-03-05 16:54:34.315 UTC: 	 Not using Singularity
DEBUG 2025-03-05 16:54:34.315 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-03-05 16:54:34.315 UTC: 	 Executing command: 'submit'
DEBUG 2025-03-05 16:54:34.315 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-03-05 16:54:34.316 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py
DEBUG 2025-03-05 16:54:34.316 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-03-05 16:54:34.324 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-03-05 16:54:34.325 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_newMINIAOD_ANA_GENv3_onlyGEMneg' already exists 
Please change the requestName in the config file
ERROR 2025-03-05 16:54:34.325 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_newMINIAOD_ANA_GENv3_onlyGEMneg' already exists 
Please change the requestName in the config file
INFO 2025-03-05 16:54:34.343 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-03-07 09:53:38.337 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-03-07 09:53:38.337 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-03-07 09:53:38.338 UTC: 	 Not using Singularity
DEBUG 2025-03-07 09:53:38.338 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-03-07 09:53:38.338 UTC: 	 Executing command: 'submit'
DEBUG 2025-03-07 09:53:38.339 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-03-07 09:53:38.341 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py
DEBUG 2025-03-07 09:53:38.341 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-03-07 09:53:38.349 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-03-07 09:53:38.353 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_newMINIAOD_ANA_GENv3_onlyGEMneg' already exists 
Please change the requestName in the config file
ERROR 2025-03-07 09:53:38.353 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_newMINIAOD_ANA_GENv3_onlyGEMneg' already exists 
Please change the requestName in the config file
INFO 2025-03-07 09:53:38.372 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-03-07 09:54:37.300 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-03-07 09:54:37.301 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-03-07 09:54:37.301 UTC: 	 Not using Singularity
DEBUG 2025-03-07 09:54:37.301 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-03-07 09:54:37.301 UTC: 	 Executing command: 'submit'
DEBUG 2025-03-07 09:54:37.302 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-03-07 09:54:37.304 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py
DEBUG 2025-03-07 09:54:37.304 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-03-07 09:54:37.306 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-03-07 09:54:37.306 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_newMINIAOD_ANAv3_onlyGEMneg' already exists 
Please change the requestName in the config file
ERROR 2025-03-07 09:54:37.306 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_newMINIAOD_ANAv3_onlyGEMneg' already exists 
Please change the requestName in the config file
INFO 2025-03-07 09:54:37.319 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-03-15 18:19:26.291 UTC: 	 CRAB Client version: v3.250217
DEBUG 2025-03-15 18:19:26.292 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-03-15 18:19:26.292 UTC: 	 Not using Singularity
DEBUG 2025-03-15 18:19:26.292 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-03-15 18:19:26.292 UTC: 	 Executing command: 'kill'
DEBUG 2025-03-15 18:19:26.292 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
ERROR 2025-03-15 18:19:26.293 UTC: 	 Error: crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py is not a valid CRAB project directory.
ERROR 2025-03-15 18:19:26.293 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py is not a valid CRAB project directory.
INFO 2025-03-15 18:19:26.311 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-03-17 09:25:59.786 UTC: 	 CRAB Client version: v3.250217
DEBUG 2025-03-17 09:25:59.786 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-03-17 09:25:59.786 UTC: 	 Not using Singularity
DEBUG 2025-03-17 09:25:59.786 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-03-17 09:25:59.786 UTC: 	 Executing command: 'submit'
DEBUG 2025-03-17 09:25:59.787 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-03-17 09:25:59.788 UTC: 	 Will use CRAB configuration file crab_MCRun4_onlyPU200_GEN_cfg.py
DEBUG 2025-03-17 09:25:59.788 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-03-17 09:25:59.796 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-03-17 09:25:59.797 UTC: 	 Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-03-17 09:25:59.797 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250217.00/lib/CRABClient/Commands/SubCommand.py", line 95, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-03-17 09:25:59.810 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-03-26 14:32:49.886 UTC: 	 CRAB Client version: v3.250318
DEBUG 2025-03-26 14:32:49.886 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-03-26 14:32:49.887 UTC: 	 Not using Singularity
DEBUG 2025-03-26 14:32:49.887 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-03-26 14:32:49.887 UTC: 	 Executing command: 'submit'
DEBUG 2025-03-26 14:32:49.890 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-03-26 14:32:49.891 UTC: 	 Will use CRAB configuration file crab_Ana_TenMuE_0_20_MINIAOD_Phase2_cfg.py
DEBUG 2025-03-26 14:32:49.891 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-03-26 14:32:49.898 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-03-26 14:32:49.900 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcRun4_TenMuE_0_20_GEN_ANA' already exists 
Please change the requestName in the config file
ERROR 2025-03-26 14:32:49.900 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcRun4_TenMuE_0_20_GEN_ANA' already exists 
Please change the requestName in the config file
INFO 2025-03-26 14:32:49.925 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-04-17 07:53:35.652 UTC: 	 CRAB Client version: v3.250318
DEBUG 2025-04-17 07:53:35.652 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-04-17 07:53:35.652 UTC: 	 Not using Singularity
DEBUG 2025-04-17 07:53:35.652 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-04-17 07:53:35.652 UTC: 	 Executing command: 'submit'
DEBUG 2025-04-17 07:53:35.652 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-04-17 07:53:35.654 UTC: 	 Will use CRAB configuration file crab_Ana_NuGunE10_MINIAOD_Phase2_cfg.py
DEBUG 2025-04-17 07:53:35.654 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-04-17 07:53:35.681 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-04-17 07:53:35.681 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_NuGunPU200_GenAna' already exists 
Please change the requestName in the config file
ERROR 2025-04-17 07:53:35.682 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250318.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_NuGunPU200_GenAna' already exists 
Please change the requestName in the config file
INFO 2025-04-17 07:53:35.777 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-05-22 09:06:07.374 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-22 09:06:07.374 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-22 09:06:07.375 UTC: 	 Not using Singularity
DEBUG 2025-05-22 09:06:07.375 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-22 09:06:07.375 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-22 09:06:07.375 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-22 09:06:07.376 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_gen_cfg.py
DEBUG 2025-05-22 09:06:07.377 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-22 09:06:07.379 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-22 09:06:07.381 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_GEN_ANAv3_allEtas_PU200_Gen' already exists 
Please change the requestName in the config file
ERROR 2025-05-22 09:06:07.381 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_GEN_ANAv3_allEtas_PU200_Gen' already exists 
Please change the requestName in the config file
INFO 2025-05-22 09:06:07.399 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-05-26 15:42:35.516 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-26 15:42:35.517 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-26 15:42:35.517 UTC: 	 Not using Singularity
DEBUG 2025-05-26 15:42:35.517 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-26 15:42:35.517 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-26 15:42:35.517 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-26 15:42:35.518 UTC: 	 Will use CRAB configuration file crab_Ana_NuGunE10_MINIAOD_Phase2_cfg.py
DEBUG 2025-05-26 15:42:35.518 UTC: 	 Loading CRAB configuration file.
ERROR 2025-05-26 15:42:35.526 UTC: 	 Error while loading CRAB configuration:
[Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/output_reduced.txt'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-05-26 15:42:35.526 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_Ana_NuGunE10_MINIAOD_Phase2_cfg.py", line 12, in <module>
    config.Data.userInputFiles = open('/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/output_reduced.txt').readlines()
FileNotFoundError: [Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/output_reduced.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_Ana_NuGunE10_MINIAOD_Phase2_cfg.py
Due to error:
[Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/output_reduced.txt'Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_Ana_NuGunE10_MINIAOD_Phase2_cfg.py", line 12, in <module>
    config.Data.userInputFiles = open('/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/output_reduced.txt').readlines()
FileNotFoundError: [Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/output_reduced.txt'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
[Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/output_reduced.txt'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-05-26 15:42:35.547 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-05-27 14:51:43.401 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-27 14:51:43.401 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-27 14:51:43.401 UTC: 	 Not using Singularity
DEBUG 2025-05-27 14:51:43.402 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-27 14:51:43.402 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-27 14:51:43.403 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-27 14:51:43.405 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py
DEBUG 2025-05-27 14:51:43.405 UTC: 	 Loading CRAB configuration file.
ERROR 2025-05-27 14:51:43.420 UTC: 	 Error while loading CRAB configuration:
[Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/lista_root_files.txt'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2025-05-27 14:51:43.420 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py", line 21, in <module>
    config.Data.userInputFiles = open('/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/lista_root_files.txt').readlines()
FileNotFoundError: [Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/lista_root_files.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/WMCore/Configuration.py", line 346, in loadConfigurationFile
    raise RuntimeError(msg)
RuntimeError: Unable to load Configuration File:
/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py
Due to error:
[Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/lista_root_files.txt'Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/WMCore/Configuration.py", line 339, in loadConfigurationFile
    modRef = load_module(cfgBaseName, modPath)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/__init__.py", line 38, in load_module
    return imp.load_module(moduleName, moduleObj[0],
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/cvmfs/cms.cern.ch/slc7_amd64_gcc12/external/python3/3.9.14-4612d00f9f0430a19291545f1e47b4a4/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py", line 21, in <module>
    config.Data.userInputFiles = open('/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/lista_root_files.txt').readlines()
FileNotFoundError: [Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/lista_root_files.txt'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Error while loading CRAB configuration:
[Errno 2] No such file or directory: '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/lista_root_files.txt'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2025-05-27 14:51:43.517 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-05-27 14:52:14.981 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-27 14:52:14.981 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-27 14:52:14.981 UTC: 	 Not using Singularity
DEBUG 2025-05-27 14:52:14.981 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-27 14:52:14.981 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-27 14:52:14.982 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-27 14:52:14.982 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py
DEBUG 2025-05-27 14:52:14.982 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-27 14:52:14.988 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-27 14:52:14.991 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_GEN_ANAv3_allEtas_PU200_Gen' already exists 
Please change the requestName in the config file
ERROR 2025-05-27 14:52:14.991 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_GEN_ANAv3_allEtas_PU200_Gen' already exists 
Please change the requestName in the config file
INFO 2025-05-27 14:52:15.054 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-05-28 09:30:01.957 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-28 09:30:01.957 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-28 09:30:01.957 UTC: 	 Not using Singularity
DEBUG 2025-05-28 09:30:01.957 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-28 09:30:01.957 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-28 09:30:01.959 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-28 09:30:01.960 UTC: 	 Will use CRAB configuration file crab_Ana_NuGunE10_MINIAOD_Phase2_cfg.py
DEBUG 2025-05-28 09:30:01.960 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-28 09:30:01.964 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-28 09:30:01.965 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_NuGunPU200_MiniaodAna_gemsegm_match_v4Prel' already exists 
Please change the requestName in the config file
ERROR 2025-05-28 09:30:01.965 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_NuGunPU200_MiniaodAna_gemsegm_match_v4Prel' already exists 
Please change the requestName in the config file
INFO 2025-05-28 09:30:01.977 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-05-28 14:11:33.780 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-28 14:11:33.781 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-28 14:11:33.781 UTC: 	 Not using Singularity
DEBUG 2025-05-28 14:11:33.781 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-28 14:11:33.781 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-28 14:11:33.782 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-28 14:11:33.784 UTC: 	 Will use CRAB configuration file crab_Ana_NuGunE10_MINIAOD_Phase2_cfg.py
DEBUG 2025-05-28 14:11:33.784 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-28 14:11:33.844 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-28 14:11:33.845 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_NuGunPU200_MiniaodAna_gemsegm_match_v4Prel' already exists 
Please change the requestName in the config file
ERROR 2025-05-28 14:11:33.846 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_NuGunPU200_MiniaodAna_gemsegm_match_v4Prel' already exists 
Please change the requestName in the config file
INFO 2025-05-28 14:11:33.966 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-05-31 10:53:10.873 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-31 10:53:10.874 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-31 10:53:10.874 UTC: 	 Not using Singularity
DEBUG 2025-05-31 10:53:10.874 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-31 10:53:10.874 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-31 10:53:10.874 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
DEBUG 2025-05-31 11:26:44.645 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-31 11:26:44.646 UTC: 	 Running on: Linux ui-al9.recas.ba.infn.it 5.14.0-427.26.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jul 17 15:51:13 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-31 11:26:44.646 UTC: 	 Not using Singularity
DEBUG 2025-05-31 11:26:44.646 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-05-31 11:26:44.646 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-31 11:26:44.647 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-31 11:26:44.649 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py
DEBUG 2025-05-31 11:26:44.649 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-31 11:26:44.764 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-31 11:26:44.776 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_miniaod_gemsegm_v2' already exists 
Please change the requestName in the config file
ERROR 2025-05-31 11:26:44.776 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_miniaod_gemsegm_v2' already exists 
Please change the requestName in the config file
INFO 2025-05-31 11:26:44.798 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-05-31 11:32:44.686 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-31 11:32:44.686 UTC: 	 Running on: Linux ui-al9.recas.ba.infn.it 5.14.0-427.26.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jul 17 15:51:13 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-31 11:32:44.686 UTC: 	 Not using Singularity
DEBUG 2025-05-31 11:32:44.686 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-05-31 11:32:44.686 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-31 11:32:44.686 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-31 11:32:44.687 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py
DEBUG 2025-05-31 11:32:44.688 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-31 11:32:44.728 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-31 11:32:44.728 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_miniaod_gemsegm_v2' already exists 
Please change the requestName in the config file
ERROR 2025-05-31 11:32:44.728 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_miniaod_gemsegm_v2' already exists 
Please change the requestName in the config file
INFO 2025-05-31 11:32:44.734 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-05-31 11:40:43.120 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-31 11:40:43.120 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-31 11:40:43.120 UTC: 	 Not using Singularity
DEBUG 2025-05-31 11:40:43.120 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-31 11:40:43.120 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-31 11:40:43.121 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-31 11:40:43.123 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py
DEBUG 2025-05-31 11:40:43.123 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-31 11:40:43.127 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-31 11:40:43.128 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_miniaod_gemsegm_v2' already exists 
Please change the requestName in the config file
ERROR 2025-05-31 11:40:43.128 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_miniaod_gemsegm_v2' already exists 
Please change the requestName in the config file
INFO 2025-05-31 11:40:43.146 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-05-31 13:03:27.195 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-31 13:03:27.195 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-31 13:03:27.195 UTC: 	 Not using Singularity
DEBUG 2025-05-31 13:03:27.195 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-05-31 13:03:27.195 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-31 13:03:27.195 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-05-31 13:03:27.196 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py
DEBUG 2025-05-31 13:03:27.196 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-05-31 13:03:27.207 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-05-31 13:03:27.207 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_miniaod_gemsegm_v2' already exists 
Please change the requestName in the config file
ERROR 2025-05-31 13:03:27.207 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_miniaod_gemsegm_v2' already exists 
Please change the requestName in the config file
INFO 2025-05-31 13:03:27.210 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-06-03 18:43:15.207 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-03 18:43:15.207 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-03 18:43:15.207 UTC: 	 Not using Singularity
DEBUG 2025-06-03 18:43:15.207 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-03 18:43:15.207 UTC: 	 Executing command: 'submit'
DEBUG 2025-06-03 18:43:15.207 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-06-03 18:43:15.208 UTC: 	 Will use CRAB configuration file crab_Ana_NuGunE10_MINIAOD_Phase2_cfg.py
DEBUG 2025-06-03 18:43:15.208 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-06-03 18:43:15.215 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-06-03 18:43:15.216 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_NuGunPU200_MiniaodAna_PU140' already exists 
Please change the requestName in the config file
ERROR 2025-06-03 18:43:15.216 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_NuGunPU200_MiniaodAna_PU140' already exists 
Please change the requestName in the config file
INFO 2025-06-03 18:43:15.533 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-06-05 07:00:46.201 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-05 07:00:46.201 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-05 07:00:46.201 UTC: 	 Not using Singularity
DEBUG 2025-06-05 07:00:46.201 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-05 07:00:46.201 UTC: 	 Executing command: 'submit'
DEBUG 2025-06-05 07:00:46.201 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-06-05 07:00:46.202 UTC: 	 Will use CRAB configuration file crab_Ana_NuGunE10_MINIAOD_Phase2_cfg.py
DEBUG 2025-06-05 07:00:46.202 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-06-05 07:00:46.206 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-06-05 07:00:46.206 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_NuGunPU200_MiniaodAna_PU50_v2' already exists 
Please change the requestName in the config file
ERROR 2025-06-05 07:00:46.206 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_NuGunPU200_MiniaodAna_PU50_v2' already exists 
Please change the requestName in the config file
INFO 2025-06-05 07:00:46.236 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-06-06 15:57:28.266 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-06 15:57:28.267 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-06 15:57:28.267 UTC: 	 Not using Singularity
DEBUG 2025-06-06 15:57:28.267 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-06 15:57:28.267 UTC: 	 Executing command: 'submit'
DEBUG 2025-06-06 15:57:28.267 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-06-06 15:57:28.268 UTC: 	 Will use CRAB configuration file crab_MCRun4_DsTau3Mu_newMiniAod_cfg.py
DEBUG 2025-06-06 15:57:28.268 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-06-06 15:57:28.275 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-06-06 15:57:28.276 UTC: 	 Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_miniaod_genInfo_NoPU_onlyGEMpos' already exists 
Please change the requestName in the config file
ERROR 2025-06-06 15:57:28.276 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 328, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab_projects/crab_140X_mcPhase2_DsTau3Mu_miniaod_genInfo_NoPU_onlyGEMpos' already exists 
Please change the requestName in the config file
INFO 2025-06-06 15:57:28.297 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-06-07 07:53:16.035 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-07 07:53:16.035 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-07 07:53:16.035 UTC: 	 Not using Singularity
DEBUG 2025-06-07 07:53:16.035 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-07 07:53:16.036 UTC: 	 Executing command: 'status'
DEBUG 2025-06-07 07:53:16.036 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
ERROR 2025-06-07 07:53:16.036 UTC: 	 Error: crab_projects/crab_140X_mcPhase2_DsTau3Mu_miniaod_genInfo_NoPU_onlyGEMposù is not a valid CRAB project directory.
ERROR 2025-06-07 07:53:16.037 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_140X_mcPhase2_DsTau3Mu_miniaod_genInfo_NoPU_onlyGEMposù is not a valid CRAB project directory.
INFO 2025-06-07 07:53:16.170 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-06-07 07:54:37.644 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-07 07:54:37.644 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-07 07:54:37.644 UTC: 	 Not using Singularity
DEBUG 2025-06-07 07:54:37.644 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-07 07:54:37.644 UTC: 	 Executing command: 'status'
DEBUG 2025-06-07 07:54:37.645 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
INFO 2025-06-07 07:54:37.652 UTC: 	 Log file is /lustrehome/felicenenna/tau3mu/CMSSW_14_0_17/src/GenAnalyser/GenAnalyzer/CrabSubmission/crab.log
DEBUG 2025-06-11 13:53:24.780 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-11 13:53:24.781 UTC: 	 Running on: Linux ui02.recas.ba.infn.it 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-11 13:53:24.781 UTC: 	 Not using Singularity
DEBUG 2025-06-11 13:53:24.781 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-06-11 13:53:24.781 UTC: 	 Executing command: 'status'
DEBUG 2025-06-11 13:53:24.781 UTC: 	 Found CRAB cache file /lustrehome/felicenenna/.crab3
